[project]
name = "python-dsa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.7.5",
    "openai>=1.95.1",
    "pandas>=2.1.4",
    "plotly>=5.24.1",
    "pycaret>=3.3.2",
    "requests>=2.32.4",
    "scikit-learn>=1.4.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.4",
    "tensorflow>=2.18.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
